
# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "tzihmqtdddlnnghyempq"

[api]
enabled = true
# Port to use for the API URL.
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
# Port to use for the local database URL.
port = 54322

[studio]
enabled = true
# Port to use for Supabase Studio.
port = 54323
# External URL of the API server that frontend connects to.
api_url = "http://localhost"

[inbucket]
enabled = true
# Port to use for the email testing server web interface.
port = 54324

[storage]
enabled = true

[functions]
[functions.openai-chat]
verify_jwt = false
