// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzihmqtdddlnnghyempq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6aWhtcXRkZGRsbm5naHllbXBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MjI2MjEsImV4cCI6MjA2MDI5ODYyMX0.uaYiIlpg8FzND_wIHyE7CM73O71PZE128gMbZxZJGS4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);